POST localhost:8080/order/place
Content-Type: application/json
X-User-Id: 1

{
  "orderItems": [
    {
      "productId": 1,
      "orderQuantity": 10
    },
    {
      "productId": 2,
      "orderQuantity": 20
    }
  ]
}