### 주문 생성
POST http://localhost:8080/order/new
Content-Type: application/json
X-User-Id: 1

{
  "orderItems": [
    {
      "productId": 1,
      "orderQuantity": 10
    },
    {
      "productId": 2,
      "orderQuantity": 20
    }
  ]
}

### 주문 처리
POST localhost:8080/order/place
Content-Type: application/json
X-User-Id: 1

{
  "orderId": 1
}